 
<?php if (($_products = $this->getNewProductCollection()) && $_products->getSize()): ?>
<div class="block block-related">
    <div class="block-title">
        <strong><span><?php echo $this->getSidebarHeading(); ?></span></strong>
    </div>
    <div class="block-content">      
        <ol class="mini-products-list" id="block-newproducts">
        <?php foreach ($_products as $_item): ?>
            <li class="item">                
                <div class="product" style="margin-left: 0px;">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(70) ?>" width="70" height="70" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
					
                    <div class="product-details">
                    <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></p>
					 
					<div class="price-box">
					<?php if($_item->getFinalPrice() < $_item->getPrice()){	?>
					<?php $priceIncludingTax = Mage::helper('tax')->getPrice($_item, $_item->getFinalPrice()); ?>
					<?php $priceExcludingTax = Mage::helper('tax')->getPrice($_item, $_item->price); ?>
					<span class="price old-price"><?php echo Mage::helper('core')->currency($priceExcludingTax, true, false); ?></span>
					<span class="price special-price">	<?php echo Mage::helper('core')->currency($priceIncludingTax, true, false); ?> </span>
					<?php }else{ ?>
					<?php $priceExcludingTax = Mage::helper('tax')->getPrice($_item, $_item->getFinalPrice()); ?>
					<span class="price"><?php echo Mage::helper('core')->currency($priceExcludingTax, true, false); ?></span>
					<?php } ?>
					</div>
				  
						<?php if($_item->isSaleable()): ?>
						<p><a href="<?php echo $_item->getProductUrl() ?>"  rel="nofollow" class="addto-cart" title="<?php echo $this->__('Buy Now') ?>"><?php echo $this->__('Buy Now') ?></a></p>
						<?php endif; ?>
					 
                    </div>
					
                </div>
            </li>
        <?php endforeach ?>
        </ol>
		<div class="actions"><a href="<?php echo $this->getUrl('') ?>newproducts"><?php echo $this->__('See All') ?></a></div>
        <script type="text/javascript">decorateList('block-newproducts', 'none-recursive')</script>
    </div>    
</div>
<?php endif ?>

 