<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<div class="page-title">
<h2><?php echo $this->getPageHeading(); ?></h2>
</div>
<?php $_productCollection=$this->getLoadedProductCollection() ?>

 
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<article class="category-products">

    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
   
	
	<ul class="products-list" id="products-list">    
    <?php foreach ($_productCollection as $_product): ?>
		<?php $_product = Mage::getModel('catalog/product')->load($_product->getEntityId()); ?>
		
        <li class="item">
           		
			<div class="list-left">
			
			<?php if($this->helper('framework')->isNewProduct($_product)):?>
				<div class="new-label"><?php echo $this->__('New') ?></div>
			<?php endif; ?>
				
			<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
				<div class="sale-label"><?php echo $this->__('Sale') ?></div>
			<?php endif; ?>
				
				
		    <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			  <?php 
			    $productId = $_product->getId();
				$_product = Mage::getModel('catalog/product')->load($productId);
				
			  ?>

<img class="remover-image" id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(254,254); ?>" alt="" />
		<img  class="hover-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(254,254); ?>" width="254" height="254" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />
</a>
			
			</div>
			
			<div class="list-center">
					<div class="f-fix">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						
						<h2 class="product-name" ><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName())?></a></h2>
						
						<div class="description"><?php echo $this->getReviewsSummaryHtml($_product, 'short') ?></div>
						
												
						<div class="desc std">
					  	<?php 
							$str = strlen($_product->getShortDescription());
							if($str <= 300 )
							{
								echo $_product->getShortDescription();  ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="link-learn">
									<?php echo $this->__('Learn More') ?>
								</a>
							<?php }
							else
							{
								echo substr($_product->getShortDescription(),0,300);  ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="link-learn">
								 <?php echo $this->__('Learn More') ?>
							   </a>
						<?php } ?>
                    	</div>
						
						<?php echo $this->getPriceHtml($_product, true) ?>
						
						<ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    	</ul>             
						
					</div>	 
                    <div class="list-right">
				
				<?php if($_product->isSaleable()): ?>
						<p>
						<button type="button" title="<?php echo $this->__('Buy Now') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span class="value-title" title="In Stock"><?php echo $this->__('Buy Now') ?></span></span></button></p>
						<?php else: ?>
						<p class="availability out-of-stock" title="<?php echo $this->__('Out of stock') ?>"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
			</div>
			</div><!-- ======== End products_list_center -->
			
			
			
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

        <?php if ($i++%$_columnCount==0): ?>
		<ul id="bestseller_standalone_page" class="products-grid">
        <?php endif ?>
		
    <?php $i=0; foreach ($_productCollection as $_product):  $i++;?>
	
		<?php $_product = Mage::getModel('catalog/product')->load($_product->getEntityId()); ?>

           <li class="item">
				<div class="product-block">
				<div class="product-block-inner">
			
				<div class="product-image-inner">
				
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			<?php 
			   $productId = $_product->getId();
				$_product = Mage::getModel('catalog/product')->load($productId);
				
			  ?>
		<img class="remover-image" id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(269,269); ?>" alt="" />
		<img  class="hover-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(269,269); ?>" width="269" height="269" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />
				</a>
				<?php if($this->helper('framework')->isNewProduct($_product)):?>
					<div class="new-label"><?php echo $this->__('New') ?></div>
				<?php endif; ?>
				
				<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
					<div class="sale-label"><span class="sale-effect"><?php echo $this->__('Sale') ?></span></div>
				<?php endif; ?>
					
                <ul class="add-to-links">
				<li class="rating-stars"><?php echo $this->getReviewsSummaryHtml($_product, 'short') ?></li>
                      <?php if ($this->helper('wishlist')->isAllow()) : ?>
                         <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php /*echo $this->__('Add to Wishlist')*/ ?></a></li>
                      <?php endif; ?>
					  
					  <li>
					  <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Buy Now') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Buy Now') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock" title="<?php echo $this->__('Out of stock') ?>"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
             	</div>
					  </li>
                      <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                         <li><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php /*echo $this->__('Add to Compare')*/ ?></a></li>
                        <?php endif; ?>
                    </ul>
	 
				</div>
				
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></h2>
				
				<?php echo $this->getPriceHtml($_product, true) ?>
				
				</div><!-- End div class product-block-->
				</div><!-- End div class product-block-inner -->
            </li>

        <?php endforeach ?>
		
        </ul> 
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
	<span style="display: none; visibility: hidden;" class="grid_default_width"></span>
</article>

<?php endif; ?> 