<?php
/**
 * 2022-08-28 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
 * 1) «count(): Parameter must be an array or an object that implements Countable
 * in app/design/frontend/templatemela/MAG100221/template/advancedmenu/top.phtml on line 2»:
 * https://github.com/etripbikes/m1/issues/6
 * 2) $_categories could be a @see Countable or an empty array:
 * @see \Mage_Catalog_Helper_Category::getStoreCategories():
 *		if (!$category->checkId($parent)) {
 *			if ($asCollection) {
 *				return new Varien_Data_Collection();
 *			}
 *			return array();
 *		}
 * https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/code/core/Mage/Catalog/Helper/Category.php#L74-L79
 */
/** @var Megnor_AdvancedMenu_Block_Topmenu $this */
/** @var Varien_Data_Tree_Node_Collection|Mage_Catalog_Model_Resource_Eav_Mysql4_Category_Collection|[] $_categories */
$_categories = $this->getStoreCategories();
if($_categories && $_categories->count()): ?>
<nav class="nav-container">
	<div class="nav-inner">
	<div id="advancedmenu">
		<?php if ($this->showHomeLink()) : ?>
		<div class="menu">
			<div class="parentMenu menu0 home_link">
				<a href="<?php echo $this->getUrl('') ?>">
					<span><?php echo $this->__('Inicio'); ?></span>
				</a>
			</div>
		</div>
		<?php endif ?>
		<?php $m=0; ?>
		 <?php $n=0; ?>
		<?php foreach ($_categories as $_category): ?>
		<?php $m++; 
			if($m<5){	 ?>
			<?php echo $this->drawAdvancedMenuItem($_category) ?>
		<?php }else{ ?>
		<div class="menu seeall">
			<div class="subparentMenu menu0 seeall">
			
				<a href="<?php echo $this->getUrl('') ?>">
					<span><?php echo $this->__('More'); ?></span>
				</a>
				<div class="subparentmenu-hover">
				<div class="super-sub">
			   <?php foreach ($_categories as $_category): ?>
				<?php $n++;
				if($n<5){}else{ ?>
				 <?php echo $this->drawAdvancedMenuItem($_category) ?>
				 <?php } ?>
			   <?php endforeach ?>
			   </div>
				</div>
			</div>
		</div>
			<?php break;	}?>
		<?php endforeach ?>


		
		<?php if ($this->isActivecustomBlock()) : 
			$custom_block_name =  Mage::getStoreConfig('advanced_menu/customblock/menucustomblock_name'); 
			$custom_block_identifier =  Mage::getStoreConfig('advanced_menu/customblock/customblock_identifier'); 
			$custom_topoffset = Mage::getStoreConfig('advanced_menu/popup/top_offset') + 0;
		?>

				<div class="custom_menu menu">
					<a><span><?php echo $custom_block_name; ?></span></a>
				<div class="customblock_inner" style="top:<?php echo $custom_topoffset; ?>px">
					<div class="custom_menu_inner">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block_identifier)->toHtml() ?> 
					</div>	
				</div>
				</div>
		<?php  endif;?>	
		
		
		<div class="clearBoth"></div>
	</div>
	
	<!-- Code for responsive menu start -->
	<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
	<div class="nav-responsive" style="display:none;"><div class="expandable"></div><span>Menu</span></div>
		<div class="responsive_menu">
			<ul id="nav" class="advanced_nav">
				<?php echo $_menu ?>
			</ul>
		</div>
	</div>	
	<!-- Code for responsive menu end -->

</nav>
<script type="text/javascript">
//<![CDATA[
var CUSTOMMENU_POPUP_WIDTH = <?php echo Mage::getStoreConfig('advanced_menu/popup/width') + 0; ?>;
var CUSTOMMENU_POPUP_TOP_OFFSET = <?php echo Mage::getStoreConfig('advanced_menu/popup/top_offset') + 0; ?>;
var CUSTOMMENU_POPUP_RIGHT_OFFSET_MIN = <?php echo Mage::getStoreConfig('advanced_menu/popup/right_offset_min') + 0; ?>;
var CUSTOMMENU_POPUP_DELAY_BEFORE_DISPLAYING = <?php echo Mage::getStoreConfig('advanced_menu/popup/delay_displaying') + 0; ?>;
var CUSTOMMENU_POPUP_DELAY_BEFORE_HIDING = <?php echo Mage::getStoreConfig('advanced_menu/popup/delay_hiding') + 0; ?>;
var megnorCustommenuTimerShow = {};
var megnorCustommenuTimerHide = {};
//]]>
</script>
<?php endif ?>

 